#!/usr/bin/env python2.7
from Tophat.tophat import TophatMain
from optparse import OptionParser
from sys import exit
if __name__ == '__main__':
		
		parser = OptionParser()
		parser.add_option("-c", "--config",help="Specify the location of the TopHat config file", dest='config')
		(opts, args) = parser.parse_args()
		if opts.config is None:
				print parser.print_help()
				print 'ERROR: No config file specified.'
				exit(1)
		else:
				TophatMain(opts.config)
